import React, { useState } from 'react';
import { useMDT } from '../context/MDTContext';
import { Role } from '../types';
import { UserPlus, Shield, X, Key, Building, UserCheck } from 'lucide-react';

interface AddEmployeeModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const AddEmployeeModal: React.FC<AddEmployeeModalProps> = ({ isOpen, onClose }) => {
  const { addUser, currentUser, users } = useMDT();
  const [name, setName] = useState('');
  const [citizenId, setCitizenId] = useState('');
  const [role, setRole] = useState<Role>('MECHANIC');
  const [department, setDepartment] = useState('Garage Workshop & Field Operations');
  const [pin, setPin] = useState('1234');
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const autoGeneratedId = `SG-${String(users.length).padStart(3, '0')}`;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) {
      setError('Nama lengkap karyawan wajib diisi.');
      return;
    }
    if (!pin.trim() || pin.trim().length < 4) {
      setError('PIN password MDT minimal 4 digit angka.');
      return;
    }

    addUser({
      name: name.trim(),
      citizenId: citizenId.trim() || autoGeneratedId,
      role,
      department: department.trim(),
      pin: pin.trim(),
    });

    // Reset and close
    setName('');
    setCitizenId('');
    setRole('MECHANIC');
    setDepartment('Garage Workshop & Field Operations');
    setPin('1234');
    setError('');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="w-full max-w-md bg-[#121214] border border-[#27272A] rounded-2xl shadow-2xl overflow-hidden text-[#E4E4E7]">
        
        {/* Header */}
        <div className="bg-[#18181B] px-6 py-4 border-b border-[#27272A] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-amber-500/10 border border-amber-500/30 rounded-lg text-amber-400">
              <UserPlus className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-white text-base">Buat Akun Karyawan Baru</h3>
              <p className="text-xs text-[#A1A1AA]">
                Moderator Access ({currentUser.name} - {currentUser.role})
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-[#A1A1AA] hover:text-white p-1 rounded-lg hover:bg-[#27272A] transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          
          {error && (
            <div className="p-3 bg-rose-500/10 border border-rose-500/30 text-rose-400 text-xs font-medium rounded-xl">
              {error}
            </div>
          )}

          {/* Full Name */}
          <div>
            <label className="block text-xs font-semibold text-[#E4E4E7] mb-1.5">
              Nama Lengkap Karyawan <span className="text-amber-400">*</span>
            </label>
            <input
              type="text"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setError('');
              }}
              placeholder="Contoh: Budi Santoso"
              className="w-full bg-[#0A0A0B] border border-[#27272A] rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-[#71717A] focus:outline-none focus:border-amber-500 font-medium"
              required
              autoFocus
            />
          </div>

          {/* ID Karyawan */}
          <div>
            <label className="block text-xs font-semibold text-[#E4E4E7] mb-1.5 flex items-center justify-between">
              <span>ID Karyawan / Citizen ID</span>
              <span className="text-[10px] text-[#A1A1AA]">Opsional (Otomatis jika kosong)</span>
            </label>
            <input
              type="text"
              value={citizenId}
              onChange={(e) => setCitizenId(e.target.value)}
              placeholder={`Otomatis: ${autoGeneratedId}`}
              className="w-full bg-[#0A0A0B] border border-[#27272A] rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-[#71717A] focus:outline-none focus:border-amber-500 font-mono"
            />
          </div>

          {/* Role Assignment */}
          <div>
            <label className="block text-xs font-semibold text-[#E4E4E7] mb-1.5 flex items-center justify-between">
              <span>Assign Role Access</span>
              <span className="text-[10px] text-amber-400 font-mono">Moderator Control</span>
            </label>
            <select
              value={role}
              onChange={(e) => setRole(e.target.value as Role)}
              className="w-full bg-[#0A0A0B] border border-[#27272A] rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-amber-500"
            >
              <option value="TRAINEE">Trainee</option>
              <option value="MECHANIC">Mechanic</option>
              <option value="TORQUE_MASTER">Torque Master</option>
              <option value="MANAGER">Manager</option>
              <option value="MODERATOR">Moderator (Full Access)</option>
            </select>
          </div>

          {/* Department */}
          <div>
            <label className="block text-xs font-semibold text-[#E4E4E7] mb-1.5">
              Departemen / Divisi
            </label>
            <select
              value={department}
              onChange={(e) => setDepartment(e.target.value)}
              className="w-full bg-[#0A0A0B] border border-[#27272A] rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-amber-500"
            >
              <option value="Garage Workshop & Field Operations">Garage Workshop &amp; Field Operations</option>
              <option value="Custom Tuning & Diagnostics">Custom Tuning &amp; Diagnostics</option>
              <option value="Repairs & Towing">Repairs &amp; Towing</option>
              <option value="Executive Management">Executive Management</option>
            </select>
          </div>

          {/* PIN Password */}
          <div>
            <label className="block text-xs font-semibold text-[#E4E4E7] mb-1.5 flex items-center justify-between">
              <span>Set PIN Password MDT (Minimal 4 Digit)</span>
              <span className="text-[10px] text-[#A1A1AA]">Gunakan untuk login</span>
            </label>
            <div className="relative">
              <Key className="w-4 h-4 text-[#71717A] absolute left-3 top-3" />
              <input
                type="text"
                maxLength={6}
                value={pin}
                onChange={(e) => {
                  setPin(e.target.value);
                  setError('');
                }}
                placeholder="PIN 4-6 digit (cth: 1234)"
                className="w-full bg-[#0A0A0B] border border-[#27272A] rounded-xl pl-10 pr-4 py-2.5 text-xs text-white placeholder-[#71717A] focus:outline-none focus:border-amber-500 font-mono tracking-widest"
                required
              />
            </div>
          </div>

          {/* Info Badge */}
          <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl text-[11px] text-[#A1A1AA] flex items-start gap-2">
            <Shield className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
            <p>
              Akun yang dibuat oleh Moderator akan langsung terdaftar di sistem MDT dan dapat digunakan karyawan untuk login.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="pt-2 flex items-center justify-end gap-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-medium bg-[#18181B] hover:bg-[#27272A] text-[#E4E4E7] transition-colors cursor-pointer"
            >
              Batal
            </button>
            <button
              type="submit"
              className="px-5 py-2 rounded-xl text-xs font-bold bg-amber-500 hover:bg-amber-400 text-black transition-colors flex items-center gap-2 shadow-md shadow-amber-500/10 cursor-pointer"
            >
              <UserPlus className="w-4 h-4" />
              <span>Simpan &amp; Buat Akun</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
